// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

// Autogenerated from `make mockery` do not edit manually

package repository

import mock "github.com/stretchr/testify/mock"

// MockIsUpdating is an autogenerated mock type for the IsUpdating type
type MockIsUpdating struct {
	mock.Mock
}

// IsUpdating provides a mock function with given fields:
func (_m *MockIsUpdating) IsUpdating() (bool, error) {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetIsUpdating provides a mock function with given fields: isUpdating
func (_m *MockIsUpdating) SetIsUpdating(isUpdating bool) error {
	ret := _m.Called(isUpdating)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(isUpdating)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
