version: "2"
services:
  app:
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - "${DOTENV}"
    environment:
      SERVER_PORT: 8000
      DB_NAME: 'covid_county'
      DB_USER: 'covid_county'
      DB_PASSWORD: 'password'
      DB_PORT: 5432
      DB_HOST: db
      LOG_LEVEL: debug
    build:
      dockerfile: infra/Dockerfile
      context: .
    volumes:
    - ./web/dist:/server/web/dist
  db:
    ports:
      - 9999:5432
    volumes:
      - ./local/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PORT: 9999
      POSTGRES_DB: covid_county
    build:
      context: ./infra/local/db
